# Generated by Django 5.0.1 on 2024-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersDepartment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dept_abbr", models.CharField(max_length=10, unique=True)),
                ("dept_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "users_department",
                "managed": False,
            },
        ),
    ]
