# Generated by Django 5.0.1 on 2024-03-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsersDepartment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dept_abbr", models.CharField(max_length=10, unique=True)),
                ("dept_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "users_department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsersIdentity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("identity_name", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "db_table": "users_identity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsersProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_image", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "users_profile",
                "managed": False,
            },
        ),
    ]
