# Generated by Django 5.0.1 on 2024-05-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authuser",
            options={
                "managed": False,
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="usersdepartment",
            options={
                "managed": False,
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="usersidentity",
            options={
                "managed": False,
                "verbose_name": "Identity/Role",
                "verbose_name_plural": "Identites/Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="usersprofile",
            options={
                "managed": False,
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterModelTable(
            name="usersdepartment",
            table="Users_department",
        ),
        migrations.AlterModelTable(
            name="usersidentity",
            table="Users_identity",
        ),
        migrations.AlterModelTable(
            name="usersprofile",
            table="Users_profile",
        ),
    ]
