# Generated by Django 5.0.1 on 2024-03-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehiclesVehiclecategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vehicle_category", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "vehicles_vehiclecategory",
                "managed": False,
            },
        ),
    ]
