# Generated by Django 5.0.1 on 2024-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclesVehicleclassification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vehicle_classification", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "vehicles_vehicleclassification",
                "managed": False,
            },
        ),
    ]
