# Generated by Django 5.0.1 on 2024-03-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicles", "0002_vehiclesvehicleclassification"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclesVehiclerfid",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vehicle_rfid", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "db_table": "vehicles_vehiclerfid",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehiclesVehicles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vehicle_plate_number", models.CharField(max_length=10, unique=True)),
                (
                    "vehicle_image",
                    models.ImageField(
                        default="vehicle_pics/vehicle.png", upload_to="vehicle_pics"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "db_table": "vehicles_vehicles",
                "managed": False,
            },
        ),
    ]
