# Generated by Django 5.0.1 on 2024-05-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicles", "0003_vehiclesvehiclerfid_vehiclesvehicles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiclesvehiclecategory",
            options={
                "managed": False,
                "verbose_name": "Vehicle Category",
                "verbose_name_plural": "Vehicle Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclesvehicleclassification",
            options={
                "managed": False,
                "verbose_name": "Vehicle Classification",
                "verbose_name_plural": "Vehicle Classifications",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclesvehiclerfid",
            options={
                "managed": False,
                "verbose_name": "Vehicle RFID",
                "verbose_name_plural": "Vehicle RFIDs",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclesvehicles",
            options={
                "managed": False,
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.AlterModelTable(
            name="vehiclesvehiclecategory",
            table="Vehicles_vehiclecategory",
        ),
        migrations.AlterModelTable(
            name="vehiclesvehicleclassification",
            table="Vehicles_vehicleclassification",
        ),
        migrations.AlterModelTable(
            name="vehiclesvehiclerfid",
            table="Vehicles_vehiclerfid",
        ),
        migrations.AlterModelTable(
            name="vehiclesvehicles",
            table="Vehicles_vehicles",
        ),
    ]
